### ISSUE TITLE
Standardize detector failure reporting and exception handling

### ISSUE THREAD

**Issue by cobya** [microsoft/component-detection#1134]
Across the various component detectors, there is a lack of standardized exception handling and error reporting via logger output. This leads to inconsistent user experience when detection for a specific ecosystem fails.

```[tasklist]
### Tasks
- [ ] Define a standard exception handling and log output practice across detectors
- [ ] Update all related exception handling
- [ ] Create a standard telemetry object which will be published on 
- [ ] Docs updates for the new detector guidance
``` 

This change will be released with other breaking changes planned for Component Detection v5. See tracking issue TBD.
